### PR TITLE
v0.4 - Added filter for beginner games and turns per week

### PR DESCRIPTION
**Pull request by Pampelmops**
Hi Jacenhan,

I made 2 small additions. Also I have 2 questions:
1. Apparently I used my actual name in my first pull request because I was using my office laptop. Any idea how to remove my name from the version tree?
2. Do you have plans to "publish" and promote your solution on planets feed? I would support this as it is very useful, at least for me. I am just not sure if someone already has done something comparable, I would like to avoid comments like "there are already 17 other solutions with many more options".

Best
Pam

### CODE REVIEW

**Comment by jacenhan** [comment]
Hi Pampelmops,

1. I will see what I can do about that, it looks like I should be able to change it through the git command line.
2. I do plan to announce this on the planets feed, hopefully within the next week or so, but there are a couple of cleanups/additions I want to make first.

I will take a look at the changes when I have a little more time, thanks for helping out!

**Comment by Pampelmops** [comment]
Hi Jacenhan,

I pushed v0.5, adding sorting and showing the date of the last quit event (resigned or dropped). Not sure if someone other than me would ask for it but for me it is particularly helpful.

This time I did not only add things but also slightly modified your existing code, I hope that is OK for you. Also the code becomes a little dirtier, e. g. I manually added a tag (lastQuitEvent) to the game object. Feel free to reject or modify my suggestion.
I don't want to bother you too much, let me know when this gets too far out of your hand.

Also I don't know how that works with my pull request. I understand my request is based on the commit, not the branch. In that case I needed to create a new pull request after your accepted (or rejected) v0.4.

Thank you
Pam

**Comment by jacenhan** [comment]
All the changes look good, I will go ahead and add them. You won't need to make a new pull request, additional commits are automatically added to it.

You might have seen that Whisperer recently released a similar but fully featured tool (http://planets.nu/_library/whisperer-scripts/gamefinder.html). I still plan to work on this in the future, but it is not as much of a priority for me. Thanks for the help!

**Comment by Pampelmops** [comment]
Yes, I have seen it in the public feed. Unfortunately I don't see a point in continuing our project. Unless for some exercise or similar reasons. Let me know if I can still be of any help in the future.

**Pull request merged**
